print"ss         ss        ssssssssssssssss       sss           sss"
print"ss         ss                     ss         sss         sss"
print"ss         ss                   ss            sss       sss"
print"ss         ss                 ss                sss   sss"
print"sssssssssssss               ss                     sss"   
print"ss         ss             ss                    sss   sss"
print"ss         ss           ss                    sss       sss"
print"ss         ss         ss                     sss         sss" 
print"ss         ss        ssssssssssssssss       sss           sss"